export default function AIServiceNotice({ degraded }) {
  if (!degraded) return null;
  return <p role="status" className="rounded-xl border p-3 text-sm" style={{ color: 'var(--aurora-text)', borderColor: 'var(--aurora-line)' }}>
    These notes were generated by our backup AI because the usual reviewer was unavailable. You can still use these notes.
  </p>;
}
